### ISSUE TITLE
additional values for sensortype

### ISSUE THREAD

**Issue by ycespb** [stac-extensions/ceos-ard#1]
Could the type property (sensor-type) values which are also useful beyond (CEOS) ARD be extended with other sensor type values and for example align with the codelist values proposed for sensorType in https://docs.ogc.org/is/17-003r2/17-003r2.html#table_16 ?

**Comment by m-mohr** [comment]
You mean `ceos_ard:type`? In principle yes, but it's meant to reflect the types defined by CEOS for ARD PFS and they only distinguish between Optical and Radar right now. So this is an upstream change, I just reflect the CEOS ARD types here. Be aware, this field is meant to identify the CEOS ARD PFS, this is not meant to be a generic sensor type field. Whenever CEOS would add another type, we'd also add it here.

**Comment by ycespb** [comment]
@m-mohr, my understanding is that the ARD "Product Family Specifications" ( or their identifiers) are sufficient and define uniquely the CEOS ARD PFS specification and the type of data they apply to (See https://ceos.org/ard/).  In my opinion, CEOS is defining the "PFS" and not specific values for "type"...  A codelist for "sensor types" makes sense even without a PFS having been defined or for metadata not intending to comply with an existing ARD PFS for such "type" of data.

**Comment by m-mohr** [comment]
>  In my opinion, CEOS is defining the "PFS" and not specific values for "type"

Don't quite agree, the type field here just reflects what is provided here (+ version and PFS):
![grafik](https://github.com/stac-extensions/ceos-ard/assets/8262166/ba69eb21-f9b1-450b-a9ef-aceac90015b4)

Whether this is needed or not is another question on its own.

>  A codelist for "sensor types" makes sense even without a PFS having been defined or for metadata not intending to comply with an existing ARD PFS for such "type" of data.

Yes, but it's not the scope of this extension.

Right now I don't see a todo for this extension. Can this be closed and/or potentially be moved to somewhere else?

**Comment by emmanuelmathot** [comment]
A quite old issue is till open on the same subject [here](https://github.com/radiantearth/stac-spec/issues/1124). Maybe it is worth considering a real sensor extension?

**Comment by m-mohr** [comment]
I agree, let's move this to https://github.com/radiantearth/stac-spec/issues/1124 - The CEOS ARD extension is certainly not the right place for it.
